<?php
require_once('tcpdf/src/Tcpdf.php'); // Sesuaikan dengan lokasi TCPDF

// Koneksi ke database
$conn = mysqli_connect("localhost", "username", "password", "nama_database");
if (!$conn) {
    die("Koneksi gagal: " . mysqli_connect_error());
}

// Query mengambil data buku beserta kategori
$query = "SELECT lb.bukuid, lb.judul, lb.penulis, lb.penerbit, lb.tahunterbit, 
                 GROUP_CONCAT(lk.namakategori SEPARATOR ', ') AS kategori
          FROM labib_buku lb
          LEFT JOIN labib_kategoribuku_relasi lkr ON lb.bukuid = lkr.bukuid
          LEFT JOIN labib_kategoribuku lk ON lkr.kategoriid = lk.kategoriid
          GROUP BY lb.bukuid";

$result = mysqli_query($conn, $query);
if (!$result) {
    die("Query Error: " . mysqli_error($conn));
}

// Buat objek PDF
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Labib');
$pdf->SetTitle('Daftar Buku');
$pdf->SetHeaderData('', 0, 'Daftar Buku', 'Generated by TCPDF');
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', 12));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', 10));
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
$pdf->SetMargins(10, 20, 10);
$pdf->SetAutoPageBreak(TRUE, 10);
$pdf->AddPage();

// Tambahkan isi tabel
$html = '<h2 style="text-align:center;">Daftar Buku</h2>';
$html .= '<table border="1" cellspacing="2" cellpadding="5">
            <thead>
                <tr style="background-color: #f2f2f2;">
                    <th>ID</th>
                    <th>Judul</th>
                    <th>Penulis</th>
                    <th>Penerbit</th>
                    <th>Tahun Terbit</th>
                    <th>Kategori</th>
                </tr>
            </thead>
            <tbody>';

while ($row = mysqli_fetch_assoc($result)) {
    $html .= '<tr>
                <td>' . htmlspecialchars($row['bukuid']) . '</td>
                <td>' . htmlspecialchars($row['judul']) . '</td>
                <td>' . htmlspecialchars($row['penulis']) . '</td>
                <td>' . htmlspecialchars($row['penerbit']) . '</td>
                <td>' . htmlspecialchars($row['tahunterbit']) . '</td>
                <td>' . (htmlspecialchars($row['kategori']) ?: 'Tidak ada kategori') . '</td>
              </tr>';
}

$html .= '</tbody></table>';

// Tampilkan dalam PDF
$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output('Daftar_Buku.pdf', 'D'); // Unduh file PDF

mysqli_close($conn);